### ISSUE TITLE
why using alpha_cump_(t+1) and alpha_cump_(t) to get x_(t-1) in DDIM ?

### ISSUE THREAD

**Issue by winnechan** [zzw-zwzhang/pytorch-ddpim#2]
The code here uses alpha_cump_(t+1) and alpha_cump_(t) to get x_(t-1) where alpha_cump has not been concatenated with 1 at the beginning. I am confused ... Can anyone help ?

https://github.com/zzw-zwzhang/pytorch-ddpim/blob/e1432a7b1a83ae9f775099c89b665ba3ea6d2e18/runner/method.py#L4

**Comment by zwzhang123** [comment]
Yeah, I also found this problem, and this code has not been updated. 1 should be concatenated in the alpha_cump.
